const cars=[
{name:'Toyota Camry',make:'Toyota',model:'Camry',year:'2018',condition:'Foreign Used',mileage:'78,000 km',type:'Sedan',price:'₦18,500,000',tag:'Available'},
{name:'Lexus RX 350',make:'Lexus',model:'RX 350',year:'2017',condition:'Foreign Used',mileage:'92,000 km',type:'Luxury',price:'₦26,500,000',tag:'Available'},
{name:'Toyota Highlander',make:'Toyota',model:'Highlander',year:'2018',condition:'Foreign Used',mileage:'86,000 km',type:'SUV',price:'₦31,000,000',tag:'Available'},
{name:'Mercedes-Benz C300',make:'Mercedes-Benz',model:'C300',year:'2016',condition:'Nigerian Used',mileage:'105,000 km',type:'Luxury',price:'₦16,800,000',tag:'Available'},
{name:'Toyota Corolla',make:'Toyota',model:'Corolla',year:'2017',condition:'Nigerian Used',mileage:'112,000 km',type:'Sedan',price:'₦12,500,000',tag:'Available'},
{name:'Honda CR-V',make:'Honda',model:'CR-V',year:'2019',condition:'Foreign Used',mileage:'74,000 km',type:'SUV',price:'₦28,000,000',tag:'Available'},
{name:'Toyota Hilux',make:'Toyota',model:'Hilux',year:'2020',condition:'Foreign Used',mileage:'68,000 km',type:'Truck',price:'₦39,500,000',tag:'Available'},
{name:'New Arrival',make:'Ask Us',model:'New Stock',year:'2024/2025',condition:'Brand New',mileage:'0 km',type:'SUV',price:'Contact for Price',tag:'New'}];
const grid=document.getElementById('catalogGrid'),count=document.getElementById('catalogCount'),empty=document.getElementById('catalogEmpty'),search=document.getElementById('catalogSearch'),condition=document.getElementById('catalogCondition'),type=document.getElementById('catalogType');
function cell(l,v){const d=document.createElement('div'),b=document.createElement('b'),s=document.createElement('span');b.textContent=l;s.textContent=v;d.append(b,s);return d}function render(){const q=search.value.trim().toLowerCase(),r=cars.filter(c=>(condition.value==='all'||c.condition===condition.value)&&(type.value==='all'||c.type===type.value)&&`${c.name} ${c.make} ${c.model}`.toLowerCase().includes(q));grid.replaceChildren();r.forEach(c=>{const card=document.createElement('article');card.className='catalog-card';const photo=document.createElement('div');photo.className='catalog-photo';const icon=document.createElement('span');icon.textContent='🚘';const badge=document.createElement('small');badge.textContent=c.tag;photo.append(icon,badge);const body=document.createElement('div');body.className='catalog-body';const title=document.createElement('h3');title.textContent=c.name;const price=document.createElement('div');price.className='catalog-price';price.textContent=c.price;const details=document.createElement('div');details.className='catalog-details';details.append(cell('MAKE',c.make),cell('MODEL',c.model),cell('YEAR',c.year),cell('CONDITION',c.condition),cell('MILEAGE',c.mileage),cell('TYPE',c.type));const a=document.createElement('a');a.className='catalog-enquire';a.target='_blank';a.rel='noopener';a.href='https://wa.me/2349077427122?text='+encodeURIComponent(`Hello King SparRow AUTOS, I am interested in the ${c.name} (${c.year}). Please confirm the price and availability.`);a.textContent='Enquire on WhatsApp';body.append(title,price,details,a);card.append(photo,body);grid.append(card)});count.textContent=r.length;empty.hidden=!!r.length} [search,condition,type].forEach(x=>x.addEventListener('input',render));document.getElementById('catalogReset').addEventListener('click',()=>{search.value='';condition.value='all';type.value='all';render()});document.querySelector('.menu-toggle').addEventListener('click',e=>{const n=document.querySelector('.nav');n.classList.toggle('open');e.currentTarget.setAttribute('aria-expanded',n.classList.contains('open'))});document.getElementById('year').textContent=new Date().getFullYear();render();
